// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

import fs from 'node:fs';
import path from 'node:path';

interface LocalDb {
  app_secrets: { key: string; value: string }[];
  app_records: { collection: string; id: string; data: unknown; updated_at?: string }[];
}

function getLocalDbPath() {
  const isServerless =
    Boolean(process.env['VERCEL'] || process.env['AWS_LAMBDA_FUNCTION_NAME']) &&
    fs.existsSync('/tmp');
  const baseDir = isServerless ? '/tmp' : process.cwd();
  return path.resolve(baseDir, '.local-db.json');
}

function loadLocalDb(): LocalDb {
  try {
    const dbPath = getLocalDbPath();
    if (fs.existsSync(dbPath)) {
      return JSON.parse(fs.readFileSync(dbPath, 'utf-8'));
    }
  } catch {}
  return { app_secrets: [], app_records: [] };
}

function saveLocalDb(db: LocalDb) {
  try {
    fs.writeFileSync(getLocalDbPath(), JSON.stringify(db, null, 2), 'utf-8');
  } catch (err) {
    console.error('[Supabase Local] Failed to save database:', err);
  }
}

function createLocalAdminClient() {
  return {
    from(tableName: 'app_secrets' | 'app_records') {
      const filters: ((row: any) => boolean)[] = [];
      let rangeSlice: [number, number] | null = null;

      const builder = {
        select(_columns?: string) {
          return builder;
        },
        eq(col: string, val: any) {
          filters.push((row: any) => row[col] === val);
          return builder;
        },
        range(from: number, to: number) {
          rangeSlice = [from, to];
          return builder;
        },
        async maybeSingle() {
          const db = loadLocalDb();
          const rows = (db[tableName] || []).filter((r) => filters.every((f) => f(r)));
          return { data: rows[0] ?? null, error: null };
        },
        async single() {
          const db = loadLocalDb();
          const rows = (db[tableName] || []).filter((r) => filters.every((f) => f(r)));
          return { data: rows[0] ?? null, error: null };
        },
        then(onfulfilled?: (val: { data: any[]; error: null }) => any) {
          const db = loadLocalDb();
          let rows = (db[tableName] || []).filter((r) => filters.every((f) => f(r)));
          if (rangeSlice) {
            rows = rows.slice(rangeSlice[0], rangeSlice[1] + 1);
          }
          const res = { data: rows, error: null };
          return Promise.resolve(onfulfilled ? onfulfilled(res) : res);
        },
        async insert(payload: any) {
          const db = loadLocalDb();
          const items = Array.isArray(payload) ? payload : [payload];
          if (!db[tableName]) db[tableName] = [];
          for (const item of items) {
            db[tableName].push(item);
          }
          saveLocalDb(db);
          return { data: items, error: null };
        },
        async upsert(payload: any) {
          const db = loadLocalDb();
          const items = Array.isArray(payload) ? payload : [payload];
          if (!db[tableName]) db[tableName] = [];
          for (const item of items) {
            const index = db[tableName].findIndex((existing: any) => {
              if (tableName === 'app_secrets') {
                return existing.key === item.key;
              } else {
                return existing.collection === item.collection && existing.id === item.id;
              }
            });
            if (index >= 0) {
              db[tableName][index] = { ...db[tableName][index], ...item };
            } else {
              db[tableName].push(item);
            }
          }
          saveLocalDb(db);
          return { data: items, error: null };
        },
      };

      return builder;
    },
  } as unknown as ReturnType<typeof createClient<Database>>;
}

function createSupabaseAdminClient() {
  const SUPABASE_URL =
    process.env['SUPABASE_URL'] ||
    process.env['VITE_SUPABASE_URL'] ||
    'https://c--f1990936-3d77-44cd-bf7c-8c12fb5f37a9-prod.lovable.cloud';
  const SUPABASE_SERVICE_ROLE_KEY = process.env['SUPABASE_SERVICE_ROLE_KEY'];

  if (SUPABASE_URL && SUPABASE_SERVICE_ROLE_KEY) {
    return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
      global: {
        fetch: createSupabaseFetch(SUPABASE_SERVICE_ROLE_KEY),
      },
      auth: {
        storage: undefined,
        persistSession: false,
        autoRefreshToken: false,
      }
    });
  }

  // When SUPABASE_SERVICE_ROLE_KEY is not configured (e.g. running locally outside Lovable Cloud),
  // fall back to local file persistence so the PIN gate and records work seamlessly.
  console.info('[Supabase] SUPABASE_SERVICE_ROLE_KEY not detected. Using local persistence (.local-db.json) for development.');
  return createLocalAdminClient();
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Load inside server handlers: const { supabaseAdmin } = await import("@/integrations/supabase/client.server");
// Top-level import is safe only in other .server.ts modules - route files and *.functions.ts ship to the client bundle.
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
